"""Add item-wise discount and tax

Revision ID: 03e485721028
Revises: bd7b309fe3ee
Create Date: 2025-10-07 17:00:34.857653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03e485721028'
down_revision = 'bd7b309fe3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('tax')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('tax')
        batch_op.drop_column('discount')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('discount', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
