"""Add tax column to Invoice model

Revision ID: bd7b309fe3ee
Revises: 99c78bb9ed1f
Create Date: 2025-10-07 15:40:49.608662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7b309fe3ee'
down_revision = '99c78bb9ed1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('tax')

    # ### end Alembic commands ###
